schemaVersion: 2.0

secrets:
  names:
    - skate-test-config-age-key

notify:
  email:
    enabled: false

machine:
  baseImage: docker.apple.com/base-images/ubi8/java17-builder:latest

package:
  dockerfile:
    perApplication: false
    dockerfilePath: Dockerfile

pipelines:
  - name: pr-check-release
    branchName: release
    timeout: 90
    build:
      template: freestyle:v4:prb
      steps:
        - wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-3.7.3-1.x86_64.rpm
        - rpm -i sops-3.7.3-1.x86_64.rpm
        - export SOPS_AGE_KEY_FILE=${BUILD_SECRETS_PATH}/skate-test-config-age-key
        - sops -d ./apple-internal/int-test-config.enc.yml > config.yml
        - curl https://downloads.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz -o apache-maven-3.8.6-bin.tar.gz
        - tar xzvf apache-maven-3.8.6-bin.tar.gz
        - rm apache-maven-3.8.6-bin.tar.gz
        - apache-maven-3.8.6/bin/mvn clean verify

  - name: pr-check-dev
    branchName: dev
    timeout: 90
    build:
      template: freestyle:v4:prb
      steps:
        - wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-3.7.3-1.x86_64.rpm
        - rpm -i sops-3.7.3-1.x86_64.rpm
        - export SOPS_AGE_KEY_FILE=${BUILD_SECRETS_PATH}/skate-test-config-age-key
        - sops -d ./apple-internal/int-test-config.enc.yml > config.yml
        - curl https://downloads.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz -o apache-maven-3.8.6-bin.tar.gz
        - tar xzvf apache-maven-3.8.6-bin.tar.gz
        - rm apache-maven-3.8.6-bin.tar.gz
        - apache-maven-3.8.6/bin/mvn clean verify

  - name: publish-release
    branchName: release
    timeout: 95
    machine:
      env:
        APP_VERSION: "1.1"
        VERSION: skate-${APP_VERSION}.#{}
        BUILD_TIME: "$(date)"
    build:
      template: freestyle:v4:publish
      steps:
        - echo "started building step"
    package:
      version: ${VERSION}
      dockerfile:
        - env:
            BASE_IMG: docker.apple.com/base-images/ubi9-minimal/java17-runtime:latest
          dockerfilePath: Dockerfile
          publish:
            - repo: docker.apple.com/aiml-di-dpi/skate/master
    finally:
      pipelineChain:
        - pipeline: dpi-skate-publish-spinnaker-chart
          buildArguments:
            - name: "SKATE_VERSION"
              value: ${VERSION}

  - name: dpi-skate-publish-spinnaker-chart
    branchName: release
    timeout: 95
    trigger:
      gitPush: false
    machine:
      env:
        HELM_CHART: "./apple-internal/helm/spinnaker-skate"
        HELM_REPO: "apple-aiml-skate-spinnaker"
    build:
      template: freestyle:v4:publish
      steps:
        - ./apple-internal/publish_chart.sh ${BUILD_PARAM_SKATE_VERSION} ${HELM_CHART} ${HELM_REPO}
    package:
      freeform:
        - publish:
            - repo: apple-helm-release-local

  - name: publish-dev
    branchRules:
      includePatterns:
        - 'dev-[^/]+'
    timeout: 95
    machine:
      env:
        APP_VERSION: "1.1"
        VERSION: skate-dev-${APP_VERSION}.#{}
        BUILD_TIME: "$(date)"
    build:
      template: freestyle:v4:publish
      steps:
        - echo "started building step"
    package:
      version: ${VERSION}
      dockerfile:
        - env:
            BASE_IMG: docker.apple.com/base-images/ubi9-minimal/java17-runtime:latest
          dockerfilePath: Dockerfile
          publish:
            - repo: docker.apple.com/aiml-di-dpi/skate/dev
    finally:
      pipelineChain:
        - pipeline: dpi-skate-dev-publish-spinnaker-chart
          buildArguments:
            - name: "SKATE_VERSION"
              value: ${VERSION}

  - name: dpi-skate-dev-publish-spinnaker-chart
    branchName: release
    timeout: 95
    trigger:
      gitPush: false
    machine:
      env:
        HELM_CHART: "./apple-internal/helm/spinnaker-skate"
        HELM_REPO: "apple-aiml-skate-dev-spinnaker"
        IMG_REPO: "aiml-di-dpi/skate/dev"
    build:
      template: freestyle:v4:publish
      steps:
        - ./apple-internal/publish_chart.sh ${BUILD_PARAM_SKATE_VERSION} ${HELM_CHART} ${HELM_REPO} ${IMG_REPO}
    package:
      freeform:
        - publish:
            - repo: apple-helm-release-local

