{{- if .Values.notary.notaryEnabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: notary-proxy-config
data:
  notary-proxy.yml: |
    server:
      proxyPort: 9090
      appHost: 127.0.0.1
      appPort: 8080
      logFile: /dev/stdout
      logLevel: INFO
      # set this to true to disable the redirect flow to IDMS and immediately reject unauthenticated requests
      # it is useful for API services without web browser clients
      disableRedirectToIdms: true
      # set this to true will disable issue notary token using daw token from the cookie,
      # this speeds up authentication latency if a Notary token is not needed
      disableIssueNotaryTokenFromDaw: true
      # set this to true will add `X-Notary-GroupIDs` header to the forwarded request
      # example header: X-Notary-GroupIDs: 1234;7890;4567
      addGroupIDsHeader: {{ .Values.notary.proxyAddGroupIDHeaders }}
      # filter the groups provided in `X-Notary-GroupIDs` header to only include the ids defined here
      groupIDsFilter: {{ .Values.notary.proxyGroupIDsFilter | toJson }}
      # if provided, the authenticated person must be a member of any of the allowed groups, otherwise a 403 will be returned.
      allowedGroupIDs: {{ .Values.notary.proxyAllowedGroupIDList | toJson }}
    appleConnect:
      appId: {{ .Values.appleConnect.appId }}
      appIdKey: {{ .Values.appleConnect.appKey }}
      rv: 1
      allowA3: true
    notary:
      # set this to true will allow notary application token to be validated from `Authorization` header
      allowApplication: true
      # if provided, the authenticated notary application must be one of the allowed applications, otherwise a 403 will be returned.
      allowedApplicationIDs: {{ .Values.notary.proxyAllowedApplicationIDList | toJson }}
      # a json map representing custom claims to include in the notary token.
      claims:
      # if domain is not provided, the notary cookie will be set to the domain is requested from.
      domain: apple.com
      audience: {{ .Values.notary.proxyAudienceList | toYaml | nindent 8 }}
{{- end }}
