{{- if .Values.notary.notaryAacEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: bpg-aac-authed
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: bpg-aac
{{- end }}
