{{- if .Values.serviceAccounts.batchProcessingGateway.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
 name: {{ .Values.serviceAccounts.batchProcessingGateway.name }}
 annotations:
   eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.batchProcessingGateway.eksServiceAccountArn }}
{{- end }}
