apiVersion: v1
kind: Service
metadata:
  name: skate-hidden-authed
  namespace: {{ .Values.skate.namespace }}
spec:
  selector:
    app: skate-hidden
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
