{{- if .Values.notary.notaryEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: notary-proxy
  namespace: {{ .Values.skate.namespace }}
type: Opaque
data:
  IDMS_APP_ADMIN_PASSWORD: {{ .Values.appleConnect.appAdminPassword | b64enc }}
  TURI_DIRECTORY_API_KEY:  {{ .Values.notary.turiKey | b64enc }}
{{- end }}
