{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.virtualClusterRole }}
rules:
  - apiGroups:
      - virtualsparkcluster.k8s.io
    resources:
      - virtualsparkclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - costattribution.k8s.io
    resources:
      - costattributions
    verbs:
      - get
      - list
      - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBinding }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.skate.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleEdit }}
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.virtualClusterRoleBinding }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccounts.skate.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.virtualClusterRole }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}