{{- if .Values.serviceAccounts.skate.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.skate.name }}
  namespace: {{ default .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.skate.eksServiceAccountARN }}
  {{- end }}
