{{- if .Values.whisper.create }}
apiVersion: v1
kind: Secret
metadata:
  name: skate-rds-secret
  namespace: skate
  annotations:
    whisper.apple.com/namespace: {{ .Values.whisper.namespace }}
    whisper.apple.com/bucket: {{ .Values.whisper.bucket }}
data: {}
{{- end }}