apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpg
  labels:
    app: bpg
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bpg
  template:
    metadata:
      labels:
        app: bpg
    spec:
      serviceAccountName: {{ .Values.serviceAccounts.batchProcessingGateway.name }}
      containers:
        - name: bpg
          image: '{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: IfNotPresent
          command: ["/opt/entrypoint.sh"]
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
              name: healthcheck
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: healthcheck
            failureThreshold: 3
            periodSeconds: 15
          volumeMounts:
            {{- if not (empty .Values.encodedConfig) }}
            - name: configuration
              mountPath: "/app/"
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.plainConfig) }}
            - name: configuration
              mountPath: "/etc/app_config/"
              readOnly: true
            {{- end }}
            - name: spark-prometheus-configuration
              mountPath: "/etc/prometheus"
              readOnly: true
          env:
            - name: MAX_HEAP_SIZE
              value: "-Xmx20G"
            - name: CONFIG_FILE_PATH
              value: "/etc/app_config/app-config.yaml"
            - name: GZ_FILE_PATH
              value: "/app/app-config.gz"
            - name: STATSD_SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: STATSD_SERVER_PORT
              value: "8125"
{{- if .Values.appleAuth }}
        - name: bgp-auth
          image: docker.apple.com/isdteam/appleconnect-proxy:1.2.134.fcd551d
          imagePullPolicy: IfNotPresent
          args:
            - -e=http://localhost:8080
            - --idms-a3-lookup-account
            - -p=9090
          env:
          {{- if .Values.appleAuthSourceFromSecret }}
            - name: APC_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appleAuthSecretName }}
                  key: apple_idms_app_id
                  optional: false
            - name: APC_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appleAuthSecretName }}
                  key: apple_idms_app_key_id
                  optional: false
            - name: APC_APP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appleAuthSecretName }}
                  key: apple_idms_app_password
                  optional: false
          {{- else }}
            - name: APC_APP_ID
              value: "181606"
          {{- end }}
            - name: APC_COOKIE_NAME
              value: acack
            - name: APC_LOGIN_URL
              value: https://idmsac.corp.apple.com/IDMSWebAuth/login
            - name: APC_VALIDATE_URL
              value: https://idmsac.corp.apple.com/IDMSWebAuth/validate
          envFrom:
            - secretRef:
                name: {{ .Values.appleAuthSecretName }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /__health
              port: 9090
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
{{- end }}
      volumes:
        - name: configuration
          {{- if not (empty .Values.encodedConfig) }}
          configMap:
            name: 'bpg-encoded-config'
            items:
              - key: 'encoded-config-yaml'
                path: 'app-config.gz'
          {{- end }}
          {{- if not (empty .Values.plainConfig) }}
          configMap:
            name: 'bpg-plain-config'
            items:
              - key: 'plain-config-yaml'
                path: 'app-config.yaml'
          {{- end }}
        - name: spark-prometheus-configuration
          configMap:
            name: 'spark-prometheus'
